---
# main tasks file for sftp nodes
- name: ensure epel repo is installed
  become: true
  yum:
    name: epel-release
    state: present

- include: sftp_ssh.yaml
- include: sftp_rssh.yaml
- include: sftp_original_users.yaml
